export enum DirectusOperator {
  EQ = '_eq',
  NEQ = '_neq',
  LT = '_lt',
  LTE = '_lte',
  GT = '_gt',
  GTE = '_gte',
  IN = '_in',
  NIN = '_nin',
  NULL = '_null',
  NNULL = '_nnull',
  CONTAINS = '_contains',
  NCONTAINS = '_ncontains',
  STARTS_WITH = '_starts_with',
  ENDS_WITH = '_ends_with',
  BETWEEN = '_between',
  NBETWEEN = '_nbetween',
  EMPTY = '_empty',
  NEMPTY = '_nempty',
}
